### ISSUE TITLE
Suggestion: Please provide option to toggle off the hack for forced 4 Neow options.

### ISSUE THREAD

**Issue by ShapeFriend** [casey-c/FilterTheSpire#3]
If such an option already exists with this mod, I would greatly appreciate being guided toward it. As stands, this lack of toggle greatly disincentives my usage of this mod in-between more serious runs of spire. Love your work, Ojb.

~Jaina

**Comment by casey-c** [comment]
Thanks for the feedback! The next update will have toggle-able options in the config menu to disable this little hack. I'll close this issue when that update is pushed - and if you're subscribed to the Workshop you should get the update automatically. Cheers.

**Comment by ShapeFriend** [comment]
Thank you for your kind contributions! Cheers.
