### ISSUE TITLE
when applying a filter with the packmaster character the searching screen come up, but then stops on "1 seed searched"

### ISSUE THREAD

**Issue by Onyxian1022** [casey-c/FilterTheSpire#37]
I dont know what info you are working for so ill help with that once I know what you are looking for

**Comment by brianyee** [comment]
I'll look into this, no promises on a fix though. Compatibility between mods can be pretty involved.

**Comment by Onyxian1022** [comment]
Thats ok if it's an easy fix I'll be happy if it isn't I just won't use it

**Comment by brianyee** [comment]
Finally had a chance to look at this. Packmaster does a lot of stuff at the start of the run and I just think it's too much of a clash between searching for the seed vs drafting the different packs at the start. Sorry, don't really know how to fix it and won't be spending more time on it

**Comment by Onyxian1022** [comment]
No problem my friend I understand and wish you luck on future endeavors
